---
title: Nate Kadlac
timezone: UTC
collections:
  blog:
    title: Blog
    output: true
  posts:
    title: Posts
    output: false
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: work
  values:
    layout: project
    header image 01: ''
    header image 02: ''
    header image 03: ''
email: nate@kadlac.com
description: Nate Kadlac is a multidisciplinary designer living in San Francisco,
  California.
baseurl: ''
url: http://kadlac.com
twitter_username: kadlac
github_username: nkadlac
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
