---
title: Nate Kadlac
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
    is featured: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
    author: Nate
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: projects
    type: projects
  values:
    layout: project
permalink: pretty
twitter:
  username: kadlac
