---
title: Nate Kadlac
timezone: UTC
collections:
  posts:
    title: Blog
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
- scope:
    path: ''
    type: work
  values:
    layout: project
    project description: 
    project subtitle: 
    header 01 image: 
    header 02 image: 
    header 03 image: 
email: nate@kadlac.com
description: Nate Kadlac is a multidisciplinary designer living in San Francisco,
  California.
baseurl: ''
url: http://kadlac.com
twitter_username: kadlac
github_username: nkadlac
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
