---
title: Nate Kadlac
timezone: UTC
collections:
  blog:
    title: Blog
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: work
  values:
    layout: project
    image: "/assets/image001.jpg"
email: nate@kadlac.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: http://kadlac.com
twitter_username: kadlac
github_username: nkadlac
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
